### ISSUE TITLE
@ionic-super-tabs/core@6.0.3 question

### ISSUE THREAD

**Issue by EdwardEvad3rs** [zyra/ionic-super-tabs#398]
For this version, the active and inactive icon color can be changed by using .scss file but indicator color was not (only white color). (--st-indicator-color no effect at all)
In the previous version, indicator color can be changed but active and inactive icon color was not. (--st-base-color-active & --st-base-color-inactive no effect at all)

Is that any way to solve this?

**Comment by ihadeed** [comment]
Can you share how you're attempting to set those variables?

I noticed that variables must be set directly on the affected element for them to work. I think setting it on the `super-tab-button` should work, but you can assign it directly to `ion-label/icon`. This is definitely something that should be improved.

```scss
super-tab-button {
  // this should work
  --st-label-color-active: yellow;
 
  ion-label {
    // this should also work
    --st-label-color-inactive: green;
  }

  ion-icon {
    --st-icon-color-active: rgba(0,0,0,0.1);
  }
}
```
