### ISSUE TITLE
Header height

### ISSUE THREAD

**Issue by Vitiumartis** [zyra/ionic-super-tabs#428]
Hello,

Does anyone know how to change header height in super-tabs?

I removed the icons in the tab button, but the height is the same.

I can't find the CSS command.

![684709562_Bildschirmfotovom2020-04-0317-31-10 png a2f8457fd1f2a8d3b80190007f73060e](https://user-images.githubusercontent.com/31731886/78596978-f7e44000-784c-11ea-8a9b-18dc56e2dc19.png)

Best regards

**Comment by jczacharia** [comment]
This should work:
```css
super-tabs-toolbar,
super-tab-button {
  height: 30px;
}
```
