### ISSUE TITLE
iOS StatusBar Bug

### ISSUE THREAD

**Issue by danielehrhardt** [zyra/ionic-super-tabs#48]
Hi,
there is a Design bug on iOS. If the Position of the Super Tabs is Bottom the Content is behind the status Bar. Look at the Screenshot. I think we must add some padding-top or somethink like that.
It is on a real device and on Ionic Serve Lab

![image](https://cloud.githubusercontent.com/assets/19570043/25926837/d333cba4-35f1-11e7-9a1e-8541a89610ab.png)

This is my tmp fix
```
// Ionic Super Tabs iOS Fix
super-tabs-container {
    ion-header {
        .toolbar {
            padding-top: calc(20px + 4px);
            min-height: calc(44px + 20px);
            .title {
                padding-top: 20px;
                height: calc(44px + 20px);
                min-height: calc(44px + 20px);
            }
        }
    }
}
```

Thank you for a fix +1

**Comment by ihadeed** [comment]
> It is on a real device and on Ionic Serve Lab

I just tested it on Ionic Serve Lab using version 2.6.0 and it looks fine. It might be fixed in the new release? can you please check and let me know.

**Comment by danielehrhardt** [comment]
yes seems to be fixed. Thank You!!

**Comment by cjdreiss** [comment]
Hello, I just started using your project today.  I'm still getting this issue in both lab and on my actual device.  

Some version info from my package.json: (i can upload more if needed)
"ionic-angular": "3.3.0",
"ionic2-super-tabs": "^2.6.2",

![img_4142](https://cloud.githubusercontent.com/assets/2102916/26601091/9af2f444-454c-11e7-889e-e6731cc8f547.PNG)

![screen shot 2017-05-30 at 3 27 13 pm](https://cloud.githubusercontent.com/assets/2102916/26601096/a0625d66-454c-11e7-9481-fd1aa5e458d0.png)

**Comment by cjdreiss** [comment]
So I did some digging, it looks like its about 20px off.  There is a css rule that is being applied to nav bars, but its very specific and since your new tabs doesnt have the ion-tabs attribute it doesn't get the styling applied.  Its adding 20px to the height of the navbars it looks like.

Here's some screenshots and the actual super long and specific selector.  NOTE: I just switched to material for all platforms, but it still has the issue. I'm sure there is a similar css selector for ios 

<img width="1364" alt="screen shot 2017-05-31 at 1 07 08 pm" src="https://cloud.githubusercontent.com/assets/2102916/26644419/95ef0562-4602-11e7-95e5-2cdaae70b56f.png">

<img width="1357" alt="screen shot 2017-05-31 at 1 07 44 pm" src="https://cloud.githubusercontent.com/assets/2102916/26644418/95ee4fdc-4602-11e7-9111-0b1426a879ec.png">



```css
.md ion-nav > .ion-page > .toolbar.statusbar-padding:first-child, 
.md ion-nav > .ion-page > ion-header > .toolbar.statusbar-padding:first-child, 
.md ion-tab > .ion-page > ion-header > .toolbar.statusbar-padding:first-child, 
.md ion-tabs > .ion-page.tab-subpage > ion-header > .toolbar.statusbar-padding:first-child, 
.md ion-menu > .menu-inner > .toolbar.statusbar-padding:first-child, 
.md ion-menu > .menu-inner > ion-header > 
.toolbar.statusbar-padding:first-child {
    padding-top: calc(20px + 4px);
    min-height: calc(56px + 20px);
}
```

I just went in to my app.scss file for now and added the following:  
```css
// fix for super-tabs on ios
.md ion-nav > .ion-page > .toolbar.statusbar-padding:first-child,
.md ion-nav > .ion-page > ion-header > .toolbar.statusbar-padding:first-child,
.md ion-tab > .ion-page > ion-header > .toolbar.statusbar-padding:first-child,
.md ion-tabs > .ion-page.tab-subpage > ion-header > .toolbar.statusbar-padding:first-child,

.md super-tab > .ion-page > ion-header > .toolbar.statusbar-padding:first-child,
.md super-tabs > .ion-page.tab-subpage > ion-header > .toolbar.statusbar-padding:first-child,

.md ion-menu > .menu-inner > .toolbar.statusbar-padding:first-child,
.md ion-menu > .menu-inner > ion-header > .toolbar.statusbar-padding:first-child {
  padding-top: calc(20px + 4px);
  min-height: calc(56px + 20px);
}


.ios ion-nav > .ion-page > .toolbar.statusbar-padding:first-child,
.ios ion-nav > .ion-page > ion-header > .toolbar.statusbar-padding:first-child,
.ios ion-tab > .ion-page > ion-header > .toolbar.statusbar-padding:first-child,
.ios ion-tabs > .ion-page.tab-subpage > ion-header > .toolbar.statusbar-padding:first-child,

.ios super-tab > .ion-page > ion-header > .toolbar.statusbar-padding:first-child,
.ios super-tabs > .ion-page.tab-subpage > ion-header > .toolbar.statusbar-padding:first-child,

.ios ion-menu > .menu-inner > .toolbar.statusbar-padding:first-child,
.ios ion-menu > .menu-inner > ion-header > .toolbar.statusbar-padding:first-child {
  padding-top: calc(20px + 4px);
  min-height: calc(44px + 20px);
}
```
